### PR TITLE
gralloc_gbm: Always map the full buffer size

### LINKED ISSUE #22: SEGV_MAPERR and graphical glitch with SW_WRITE_OFTEN flagged buffers
Hello,
This one is really tricky for my limited hobbyst knowledge, 

I'm opening in order to triage, as this is the last issue preventing the use of gbm_gralloc as default gralloc in android-x86 with Android R - NOTE: Android R requires hwbinder composer@2.1-service and gbm_gralloc needs to become the default gralloc

I'm opening a ticket for a problem happening only with gbm_gralloc and logged on r600 (AMD TURKS)
but it is happening also with radeonsi and nouveau.

As a comparison the problem does not happen with minigbm with the same GPUs and mesa version

```
0x76d2d8fe6ba0: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
0x76d2d8fe8d10: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
0x76d2d8fea250: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
```

0x933 flags correspond to
`GRALLOC_USAGE_HW_COMPOSER | GRALLOC_USAGE_HW_TEXTURE | GRALLOC_USAGE_SW_WRITE_OFTEN | GRALLOC_USAGE_SW_READ_OFTEN`

Android R android-11.0.0_r17 mesa 21.0.1

ResolverActivity_20210405-152214

I'm adding logs in the attachments: `tombstone`, `addr2line`, `modetest` and `dumpsys SurfaceFlinger`

[logcat_gbm_gralloc_glitch.zip](https://github.com/robherring/gbm_gralloc/files/6259859/logcat_gbm_gralloc_glitch.zip)

[tombstone_00_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259762/tombstone_00_gbm_gralloc_glitch.txt)

[addr2line_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259772/addr2line_gbm_gralloc_glitch.txt)

[modetest_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259789/modetest_gbm_gralloc_glitch.txt)

[dumpsys_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259778/dumpsys_gbm_gralloc_glitch.txt)

Chicken Invaders 3 is also affected as explained below, there is a top pane that should show Ads

Chicken_Invaders_3_20210405-173449

### PR DESCRIPTION
**Pull request by aleasto**
Fixes: #22

### CODE REVIEW

**Comment by aleasto** [comment]
I could not find a gralloc hal that actually uses the passed-in coordinates (other than for checking whether they are a valid region).
Examples: [default(ashmem)](https://cs.android.com/android/platform/superproject/+/master:hardware/libhardware/modules/gralloc/mapper.cpp;l=159), [qcom](https://cs.android.com/android/platform/superproject/+/master:hardware/qcom/sm7250/display/gralloc/QtiMapper.cpp;l=178), [google(mali)](https://cs.android.com/android/platform/superproject/+/master:hardware/google/gchips/gralloc3/src/mali_gralloc_bufferaccess.cpp;l=349), [minigbm](https://cs.android.com/android/platform/superproject/+/master:external/minigbm/drv.c;l=524;bpv=0;bpt=1)

This sounds like a bug in Skia, but let's make it happy.

**Comment by aleasto** [comment]
@robherring Can you review this patch?

@maurossi you're welcome to test this on your devices, should work!

**Comment by scutwukai** [comment]
> I could not find a gralloc hal that actually uses the passed-in coordinates (other than for checking whether they are a valid region). Examples: [default(ashmem)](https://cs.android.com/android/platform/superproject/+/master:hardware/libhardware/modules/gralloc/mapper.cpp;l=159), [qcom](https://cs.android.com/android/platform/superproject/+/master:hardware/qcom/sm7250/display/gralloc/QtiMapper.cpp;l=178), [google(mali)](https://cs.android.com/android/platform/superproject/+/master:hardware/google/gchips/gralloc3/src/mali_gralloc_bufferaccess.cpp;l=349), [minigbm](https://cs.android.com/android/platform/superproject/+/master:external/minigbm/drv.c;l=524;bpv=0;bpt=1)
> 
> This sounds like a bug in Skia, but let's make it happy.

nice work !! praise you

**Comment by maurossi** [comment]
> @maurossi you're welcome to test this on your devices, should work!

I have tested with r600, radeonsi on Android 11 r-x86, issue #22 is fixed on launcher selection ResolverActivity dialogue and error dialogues

**Pull request merged**
